"""Phased 300M: reward component returns (unweighted episodic returns, symlog).

Reads pre-computed TB CSV caches from figures/tb_cache_*.csv (generated by an
offline script that extracts scalars from the TB events file to keep this plot
fast to regenerate). Skipped gracefully if no cache is present.

Output: figures/phased_300M_reward_components.pdf
"""

import matplotlib.pyplot as plt
import pandas as pd
from _style import FIGURES_DIR, M, apply_style, smooth

apply_style()

COMP_TAGS = {
    "WinDrawLoss": "charts__episodic_return__WinDrawLossRewardFunction",
    "ResourceGather": "charts__episodic_return__ResourceGatherRewardFunction",
    "ProduceWorker": "charts__episodic_return__ProduceWorkerRewardFunction",
    "ProduceBase": "charts__episodic_return__ProduceBaseRewardFunction",
    "ProduceBarracks": "charts__episodic_return__ProduceBarracksRewardFunction",
    "Attack": "charts__episodic_return__AttackRewardFunction",
    "ProduceLight": "charts__episodic_return__ProduceLightUnitRewardFunction",
    "ProduceHeavy": "charts__episodic_return__ProduceHeavyUnitRewardFunction",
    "ProduceRanged": "charts__episodic_return__ProduceRangedUnitRewardFunction",
}
COMP_COLORS = [
    "#d62728",
    "#2ca02c",
    "#1f77b4",
    "#9467bd",
    "#17becf",
    "#ff7f0e",
    "#8c564b",
    "#bcbd22",
    "#e377c2",
]

fig, ax = plt.subplots(figsize=(10, 5))
has_data = False
for (name, safe_tag), color in zip(COMP_TAGS.items(), COMP_COLORS):
    path = FIGURES_DIR / f"tb_cache_{safe_tag}.csv"
    if not path.exists():
        continue
    df = pd.read_csv(path)
    ax.plot(
        M(df["step"]), smooth(df["value"], 40), color=color, linewidth=1.3, alpha=0.85, label=name
    )
    has_data = True

if not has_data:
    print("  No TB cache for reward components — skipping")
    raise SystemExit(0)

phase_M = [100, 150, 250, 280]
for ps in phase_M:
    ax.axvline(ps, color="#888", ls="--", alpha=0.4, lw=0.8)

ax.set_xlabel("Training steps (M)")
ax.set_ylabel("Unweighted episodic return")
ax.set_yscale("symlog", linthresh=1)
ax.set_xlim(0, 300)
ax.legend(loc="lower left", ncol=3, fontsize=7.5)

fig.tight_layout()
out = FIGURES_DIR / "phased_300M_reward_components.pdf"
fig.savefig(out, bbox_inches="tight")
print(f"Saved: {out}")
